version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: l0lc4t5
#      MONGO_INITDB_DATABASE: campaigns

  db-seed:
    container_name: db-seed
    build:
      context: ./api
      dockerfile: Dockerfile-db-seed
    environment:
      MONGO_URL: mongodb://mongo:27017/campaigns
    depends_on:
      - mongo

  api:
    container_name: api
    build: ./api
    volumes:
      - './api:/usr/src/api'
    environment:
      MONGO_URL: mongodb://mongo:27017/campaigns
    ports:
      - '3000:3000'
    depends_on:
    - mongo
    - db-seed

  client:
    container_name: client
    build: ./client
    volumes:
    - './client:/usr/src/app'
    ports:
    - '8080:8080'
    depends_on:
    - api