version: '3'
services:

  mongo:
    container_name: mongo
    logging:
      driver: none  # reduce noise so we can see test output
    image: mongo
    ports:
    - '27017:27017'

  api:
    container_name: api
    build: ./api
    command: npm run test
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
    - mongo
