version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  db-seed:
    container_name: db-seed
    build:
      context: ./api
      dockerfile: Dockerfile-db-seed
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - mongo

  api:
    container_name: api
    build: ./api
    command: npm run startdev
    volumes:
      - './api:/usr/src/api'
    environment:
      MONGO_URL: mongodb://mongo:27017
    ports:
      - '3000:3000'
    depends_on:
    - mongo
    - db-seed

  client:
    container_name: client
    build: ./client
    command: npm run startdev
    volumes:
      - './client:/usr/src/client'
    environment:
      API_URL: http://localhost:3000/api
    ports:
      - '8080:8080'
    depends_on:
      - api