version: '3'
services:

  mongo:
    image: mongo
    volumes:
      - './docker-entrypoint-initdb.d/campaigns.js:/docker-entrypoint-initdb.d/campaigns.js'
    environment:
       MONGO_INITDB_DATABASE: campaigns

  api:/campaigns.js:
    build: ./api
    command: npm run startdev
    volumes:
      - './api:/usr/src/api'
    environment:
      MONGO_URL: mongodb://mongo:27017/campaigns
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - mongo