version: '3'

services:

  mongo:
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: l0lc4t5
#      MONGO_INITDB_DATABASE: campaigns

  api:
    build: ./api
    environment:
      MONGO_URL: mongodb://mongo:27017/campaigns
    ports:
      - '3000:3000'
    depends_on:
    - mongo

  client:
    build: ./client
    ports:
    - '8080:8080'
    depends_on:
    - api